version: "3"
services:
  # WEBサーバ
  web:
    build: ./
    volumes:
      - ./html:/var/www/html
#      - ./config/.bashrc:/root/.bashrc
    ports:
      - "19080:80"
    tty: true
    stdin_open: true
    privileged: true
    links:
      - db
    environment:
      - DB_HOST=mysql
      - DB_PORT=19306
      - DB_DATABASE=spotify
      - DB_USERNAME=root
      - DB_PASSWORD=jGL0V!k3pFW3
  #DB
  db:
    image: mysql:5.7
    ports:
      - '19306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=!5A5wRGdGBXv
      - MYSQL_DATABASE=spotify
      - MYSQL_USER=root
      - MYSQL_PASSWORD=jGL0V!k3pFW3
    volumes:
      - ./db-data:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
    tty: true
    stdin_open: true
    privileged: true
    user: "1000:50"
    command: "--innodb_use_native_aio=0"